"""removed comp_id 

Revision ID: 311ccaa64603
Revises: e4f7a50850c9
Create Date: 2026-10-02 11:32:34.328510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311ccaa64603'
down_revision: Union[str, Sequence[str], None] = 'e4f7a50850c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('datasets_company_id_fkey'), 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('datasets_company_id_fkey'), 'datasets', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
