"""add role to user

Revision ID: e4f7a50850c9
Revises: d6ad3d5c646d
Create Date: 2026-09-05 16:21:25.655813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f7a50850c9'
down_revision: Union[str, Sequence[str], None] = 'd6ad3d5c646d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.execute('''update users set role = 'member' where role is null''')
    op.alter_column("users","role",nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
